- ansible.builtin.import_playbook: playbooks/setup-sudoers.yml
- ansible.builtin.import_playbook: playbooks/harden-ssh.yml
- ansible.builtin.import_playbook: playbooks/patch-proxmox.yml
- ansible.builtin.import_playbook: playbooks/update-os.yml
