# Example usage: ansible-playbook state.yml
# This playbook deploys my whole homelab.

---

- name: Play for all machines
  hosts: all
  roles:
    - {role: common, tags: common}
    - {role: artis3n.tailscale, tags: tailscale}
  vars:
    tailscale_args: --ssh
  vars_files:
    - vault.yml

- name: Play for proxmox machines
  hosts: cupcakes
  roles:
    - {role: proxmox, tags: proxmox}

- name: Play for Wings machines
  become: true
  hosts:
    - bakery
    - oci1
    - oci2
  roles:
    - {role: geerlingguy.docker, tags: docker}
    - {role: wings, tags: wings}
