# Example usage: ansible-playbook state.yml
# This playbook deploys my whole homelab.

---

- name: Play for all machines
  hosts: 'all'
  roles:
    - 'common'
    - 'artis3n.tailscale'
  vars:
    tailscale_args: "--ssh"
  vars_files:
    - 'vault.yml'

- name: Play for proxmox machines
  hosts: 'cupcakes'
  roles:
    - 'proxmox'
