# Example usage: ansible-playbook state.yml
# This playbook deploys my whole homelab.

---

- name: Play for all machines
  hosts: all
  vars:
    tailscale_args: "--ssh"
  roles:
    - {role: common, tags: common}
    - {role: artis3n.tailscale, tags: tailscale}
  vars_files:
    - vault.yml

- name: Play for proxmox machines
  hosts: cupcakes
  roles:
    - {role: proxmox, tags: proxmox}

- name: Play for docker machines
  hosts:
    - hostess
    - bakery
    - oci1
    - oci2
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
  roles:
    - {role: geerlingguy.pip, tags: pip, become: true}
    - {role: geerlingguy.docker, tags: docker, become: true}

- name: Play for Pterodactyl machines
  hosts:
    - hostess
  roles:
    - {role: pterodactyl, tags: pterodactyl, become: true}
  vars_files:
    - vault.yml

- name: Play for Wings machines
  hosts:
    - bakery
    - oci1
    - oci2
  roles:
    - {role: wings, tags: wings, become: true}
