- name: Ensure required packages are installed
  ansible.builtin.apt:
    update_cache: true
    package:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Ensure distribution-provided docker packages are absent
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Add docker.com key
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker.com repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install docker from the docker.com repository
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Docker is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
