- name: Ensure required packages are installed
  ansible.builtin.apt:
    update_cache: true
    package:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Ensure distribution-provided docker packages are absent
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Configure docker repository
  block:
    - name: Download docker gpg key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Configure docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        update_cache: true
        filename: docker

- name: Install docker from the docker.com repository
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Docker is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
