---
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart cron
  become: true
  ansible.builtin.service:
    name: cron
    state: restarted
