- name: Install dependencies
  ansible.builtin.include_tasks: deps.yml

- name: /var/www/pterodactyl is present
  ansible.builtin.file:
    path: /var/www/pterodactyl
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: Detect existing install and check for available upgrade
  ansible.builtin.include_tasks: detect_install_upgrade.yml

- name: .env file is installed
  ansible.builtin.template:
    src: env.j2
    dest: /var/www/pterodactyl/.env
    owner: www-data
    group: www-data
    mode: 0600

- name: Install Panel
  ansible.builtin.include_tasks: install.yml
  when: not pterodactyl_panel_envfile.stat.exists

- name: Upgrade Panel version
  ansible.builtin.include_tasks: upgrade.yml
  when: (pterodactyl_panel_detected_version|default(pterodactyl_panel_version) != pterodactyl_panel_version)

- name: Schedule cronjob is present
  ansible.builtin.cron:
    name: Pterodactyl Panel - Schedule
    job: php /var/www/pterodactyl/artisan schedule:run >> /dev/null 2>&1

- name: Install pteroq service file
  ansible.builtin.copy:
    src: pteroq.service
    dest: /etc/systemd/system/pteroq.service
    owner: root
    group: root
    mode: 0644
  notify: Restart pteroq

- name: Enable and start redis-server
  ansible.builtin.systemd:
    name: redis-server
    enabled: true
    state: started

- name: Enable and start pteroq.service
  ansible.builtin.systemd:
    name: pteroq.service
    enabled: true
    state: started
