- name: Install Pterodactyl
  become: true
  block:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        package:
          - curl
          - tar
          - unzip
          - git
          - nginx
    - name: Create required directory structure
      ansible.builtin.file:
        path: /var/www/pterodactyl
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Download Pterodactyl
      ansible.builtin.unarchive:
        src: https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz
        dest: /var/www/pterodactyl
        remote_src: true
    - name: Set correct permissions for storage and bootstrap/cache
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 0755
        recurse: true
      loop:
        - /var/www/pterodactyl/storage/
        - /var/www/pterodactyl/bootstrap/cache/
    # TODO: cp.env.example .env https://pterodactyl.io/panel/1.0/getting_started.html#installation
