- name: Update APT cache and upgrade packages
  become: true
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade packages (this may take a while)
      ansible.builtin.apt:
        upgrade: safe
