- name: add sudoers with ssh keys
  hosts: all
  become: yes
  gather_facts: no
  vars:
    users:
      - name: caycehouse
        github: caycehouse
        password: $6$zpn8R2g0kxjloJ3J$UpMKBvc/IV.FC76GEEyK9a.tgzjSFJ5ZE.yC7Wxz/.ap07j29Oxm0.gV4kUV6ChcQJD5xUIFgsgo1DXIXC0ho0
  tasks:
    - name: add sudo
      apt:
        name: sudo
        state: present
    - name: add user
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        shell: /bin/bash
      with_items: "{{ users }}"
    - name: enable passwordless sudo
      lineinfile:
        dest: /etc/sudoers.d/99-ansible-users
        state: present
        mode: 0440
        create: yes
        regexp: '^{{ item.name }}'
        line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      with_items: "{{ users }}"
    - name: add keys from github
      authorized_key:
        key: "https://github.com/{{ item.github }}.keys"
        user: "{{ item.name }}"
      with_items: "{{ users }}"
